apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-port.yaml
- deployment.yaml

images:
- name: vinaybalamuru/boot-deploy:latest
  newName: vinaybalamuru/boot-deploy
  newTag: 0.0.0